name: Build oLinker Windows Executable

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      run: |
        go mod tidy
        $env:GOOS="windows"
        $env:GOARCH="386"
        go build -ldflags="-H windowsgui" -o oLinker.exe ./cmd/olinker

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: oLinker-windows-386
        path: oLinker.exe
